### ISSUE TITLE
Requesting support for GovCloud

### ISSUE THREAD

**Issue by die7fox** [aws-quickstart/quickstart-microsoft-sharepoint#10]
Template fails when trying to deploy in either GovCloud region. Failure occurs when the template tries to create AD Stack:

`Partition "aws" is not valid for resource "arn:aws:ssm:us-gov-east-1:435842589984:parameter/CFN-ADPassword-UnkEe9oT6SXj". (Service: AmazonldentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 8l983tba9-1e56-11e 9-ba5b>-0df3659e6b2b)`

It appears to be a problem with the ARN, but I don't see a way to correct it in the Quick Start template.

**Comment by virtlima** [comment]
This is due to an update in the Active Directory Quick Start where we are utilizing AWS Secrets Manager to Store Credentials. Currently AWS Secrets Manager is not available in GovCloud, we will work on updating the templates to accommodate this and apologize for the inconvenience. In the interim if you modify the following [line](https://github.com/aws-quickstart/quickstart-microsoft-sharepoint/blob/b2c1afbd6a95d941af86b8bbc440b11508e0898b/templates/SharePoint_2016_Master.template#L831) to point to ad-1-old.template to utilize the previous version which doesn't utilize Secrets Manager it should work. Please let us know if this is not the case.

**Comment by die7fox** [comment]
Appreciate your feedback. When I modify that line, AD creation fails with an S3 error: "The specified key does not exist." Perhaps the template is no longer available?

**Comment by virtlima** [comment]
Looking into this a bit more, the issue you are hitting is not due to that AD update as that submodule update had not been pushed to this project yet. However, we have a plan for regions that do not have Secrets manager. Looking a bit more at the error above it is as you mentioned a problem with the ARN that is being formed in the IAM Policy for Access to the [SSM Params](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/53d33e1cdff091e1bb0e8a794a850b606ecf0af7/templates/ad-1-old.template#L498-L523).  We will work on adding in a similar condition to the resource definition as we have with [S3 Buckets](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/53d33e1cdff091e1bb0e8a794a850b606ecf0af7/templates/ad-1-old.template#L477-L490). You can try adding that into the resource part of the policy and testing again.

**Comment by virtlima** [comment]
Die7fox, 
Wanted to follow up on this, I am working on merging this into sharepoint but wanted to provide an example of the update we will make to support GovCloud better. The template [here](https://github.com/virtlima/quickstart-microsoft-activedirectory/blob/develop/templates/ad-1-ssm.template) represents the updated AD Quickstart using AWS Systems Manager to store secrets. However, the area that was modified that will help you with your issue is this [section](https://github.com/virtlima/quickstart-microsoft-activedirectory/blob/c4f5072ee2b0487a783028c9fbab32939657175a/templates/ad-1-ssm.template#L614-L637). In that section I am utilizing the [AWS::Partition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html) Pseudo Parameter to construct the ARN in the policy. Using this will ensure that the correct ARN is formulated for Gov Cloud. Once this is tested and rolled into this project I will close this out.

**Comment by die7fox** [comment]
This is great news. Thanks for your efforts and I look forward to the end result.

**Comment by virtlima** [comment]
I should have closed this out awhile ago, apologize for the delay. In the Repo is a template named [SharePoint_2016_Master_SSM.template](https://github.com/aws-quickstart/quickstart-microsoft-sharepoint/blob/master/templates/SharePoint_2016_Master_SSM.template) that does not use Secrets Manager. This can be used for GovCloud until Secrets Manager is available in Gov Cloud.
